puppetlabs/puppetfactory

- pltraining-puppetfactory/README.md
- puppetfactory/lib/puppetfactory/helpers.rb
- puppetfactory/lib/puppetfactory/monkeypatches.rb
- puppetfactory/lib/puppetfactory/plugins/github.rb
- puppetfactory/views/users.erb
This adds a link to the user's last github commit, if available.
TRAINTECH-449 #resolved #time 45m
> Add last commit message to the github view

- puppetfactory/lib/puppetfactory/plugins/gitviz.rb
- puppetfactory/public/explain-git-with-d3/css/explaingit.css
- puppetfactory/public/explain-git-with-d3/index.html
> gitviz style tweaks

- pltraining-puppetfactory/metadata.json
> Update the chocolatey module dependency to use the same one that

- pltraining-puppetfactory/files/default.conf
- pltraining-puppetfactory/files/html/404.html
- pltraining-puppetfactory/files/html/50x.html
- pltraining-puppetfactory/manifests/proxy.pp
(note, it won't actually use the 404 page right now, because that's handled by Puppetfactory. I'll come back to that another time.)
TRAINTECH-413 #resolved #time 45m
> Nicer error page that doesn't scream at you

- puppetfactory/lib/puppetfactory/plugins/code_manager.rb
- puppetfactory/lib/puppetfactory/plugins/r10k.rb
If we're only using a single control repo, then environments are created
when the user creates a branch in the control repo. We don't need to add
sources for them.
> Only create sources when running in peruser mode

- puppetfactory/lib/puppetfactory/plugins/shell_user.rb
Make this match the regex in use
> Correct the error message

- puppetfactory/lib/puppetfactory/dashboard/rake_tasks.rb
- puppetfactory/lib/puppetfactory/dashboard/spec_helper.rb
- puppetfactory/lib/puppetfactory/plugins/dashboard.rb
TRAINTECH-822 #resolved #time 2h
> More reliable and less opaque tests

- puppetfactory/lib/puppetfactory/plugins/gitea.rb
Add a Gitea plugin to clone the control repo into Gitea from GitHub
and manage Gitea accounts, collaborators, and branches for users in
PuppetFactory.
> Add Gitea plugin

- pltraining-puppetfactory/manifests/dockerenv.pp
- pltraining-puppetfactory/manifests/init.pp
- pltraining-puppetfactory/manifests/params.pp
- pltraining-puppetfactory/templates/centos.dockerfile.erb
Adds support for a "default_class" parameter which will be applied to student nodes when they first boot.  The default points to course_selector, but this will allow us to set up profiles in the classroom module that apply different course_selector profiles to the nodes.
> Default class to apply to student nodes

- puppetfactory/lib/puppetfactory/plugins/classification.rb
TRAINTECH-586 #resolved #time 30m
> Friendlier environment group names

- views/logs.erb
This makes the timeout work correctly
> Wrap loadLogs in anonymous function

- lib/puppetfactory.rb
- public/css/style.css
- public/js/usermanagement.js
- views/index.erb
- views/newuser.erb
TRAINTECH-1201 #resolved #time 4h
Users will now get the new user page first thing.  They must create
a user or log in as the admin to proceed.  Instructions on how to
create the account and what the account is included.  This is to
improve the workflow by getting this one time step out of the way
right away.
> (TRAINTECH-1201) Puppetfactory New User Page

- README.md
TRAINTECH-1215 #resolved #time 5m
Readme was accidentally removed earlier. Copied from pltraining-
puppetfactory.
> (TRAINTECH-1215) Add Puppetfactory Readme Back

- public/css/style.css
- views/newuser.erb
Remove extra instructions and explanations and focus purely on
new user form.
> Simplify the new user screen

- public/css/style.css
- views/users.erb
The newusers template from the home page could be reused on the
users page, so I reused it.  Minor css changes to accommodate it.
> Reuse the newuser Template on the Users Page

- public/css/style.css
- views/logs.erb
Nothing significant; cleaning up selectors, enlarging some fonts, fixing an issue where content was overlapping the header.
> Style fixes

- lib/puppetfactory.rb
- public/css/style.css
- public/js/scripts.js
- views/index.erb
TRAINTECH-1203 #resolved #6h
This is not nearly robust enough nor a real logout since it
remembers entered credentials, but it's a decent fake.  Explored
warden and related gems, but could not find a simple way to drop
it in for handling authenication.
> (TRAINTECH-1203) PF Admin Logout Functionality

- templates/puppet.conf.erb
Removed the misconfigured directories for the classes.txt file so
they line up with the labs in puppet practitioner.
> Update puppet.conf.erb to remove misconfigured dir

- lib/puppetfactory.rb
- public/css/style.css
- views/currentuser.erb
- views/index.erb
- views/newuser.erb
- views/shell.erb
- views/users.erb
> Hide users

- lib/puppetfactory/plugins/docker.rb
TRAINTECH-1359 #resolved #time 4
> We can't share the yum repo!

- lib/puppetfactory/plugins/gitea.rb
Executing a string leaves code open to shell injection. Instead, we use
RestClient to make HTTP requests and then parameterized commands.
TRAINTECH-1372 #resolved #time 4h
> Remove shell injection vulnerabilities

- lib/puppetfactory/plugins/gitea.rb
If multiple users attempted to create accounts more or less
simultaneously, then we'd sometimes run into conditions where git would
run over itself trying to check out multiple branches at the same time.
This just flocks the directory so that only one will happen at a time.
I think this is as good as we're going to get for now. Gitea is
surprisingly fragile. Luckily, we should be able to just delete &
recreate (or repair) the user. I'll think about some sane retry logic.
Builds atop #243
TRAINTECH-1371 #time 1h
> Remove race conditions on branch creation

- lib/puppetfactory.rb
Have the endpoint that activates the user check that the user exists.
> (MAINT) Have Activate User Check for Existing User

- views/index.erb
TRAINTECH-1391 #resolved #time 10m
Add a link to the Gitea repository for students.
> (TRAINTECH-1391) Add Link to Gitea Repo

- public/js/usermanagement.js
- views/userlogin.erb
Fixed the bug where the login form was not getting matched to a
route.  Now creates the full route in JS on click
> (MAINT) Fix User Login Issue

- views/currentuser.erb
JS selector was looking for the ID, not the class user-logout, so
updated the view to match.
> (MAINT) Fix User Logout Error

- public/css/style.css
- public/js/usermanagement.js
- views/currentuser.erb
- views/index.erb
- views/newuser.erb
- views/userlogin.erb
What the new interface looks like
> Courses 1403

- hammertime.sh
This is just a dumb script that pounds the machine it's running on by
creating 19 users and then running Puppet in parallel and deploying code
quickly and regularly for a few hours.
It should provide a relatively reasonable simulation of what a classroom
experience might be.
> (maint) stupid load testing script

- public/css/style.css
- public/js/scripts.js
- views/shell.erb
TRAINTECH-1404 #resolved #time 1d
Make the SSH login text available after student user has logged in.
JS was configured to allow future toggles to be easily added.
New ? toggle, visible and not.
> (TRAINTECH-1404) SSH Help After Login

- views/currentuser.erb
TRAINTECH-1514 #resolved #time 15m
> Add back deploy spinner

- views/shell.erb
TRAINTECH-1084 #resolved #time 15m
> Add username to alternate login

- lib/puppetfactory/plugins/docker.rb
We shouldn't need to map so many things. We don't really want to share all this.
TRAINTECH-1553 #resolved #time 15m
> We shouldn't need to map so many things
