puppetlabs/puppetfactory

- puppetfactory/views/users.erb
Webserver URL is a little bit more descriptive. Sandbox confused some people as to what sort of sandbox was meant.
> Change the heading name to help avoid confusion

- puppetfactory/views/logs.erb
This will scroll to bottom on first load, then keep it scrolled as more
content is added--unless the user has scrolled away.
> Keep the logs scrolled to bottom

- puppetfactory/lib/puppetfactory/plugins/user_environment.rb
This is gross. But it will keep deliveries this week from failing. Next week we can roll out the tested deploy workflow and update the materials to match.
> don't deploy if editing code live

- pltraining-puppetfactory/manifests/init.pp
- pltraining-puppetfactory/manifests/params.pp
- puppetfactory/lib/puppetfactory/plugins/user_environment.rb
Even when editing code in ~/puppetcode, this enforces the need to
actively choose to deploy your codebase. This will copy all the code
from the user's environment in code-staging to codedir, make sure that
it's owned by 'pe-puppet', and then clear the environment cache.
This is marked WIP only because I'd like to test it more. Feel free to
unmark it and merge if you do the necessary testing.
TRAINTECH-896 #resolved #time 3h
> This enforces the separation between staging & live

- puppetfactory/bin/pfsh
See TRAINTECH-1162
copied from the ticket:
> This change in puppetclassify caused the behavior change: https://github.com/puppetlabs/puppet-classify/pull/18
> Puppetclassify needs this set to even initialize

- public/explain-git-with-d3/css/explaingit.css
Especially when embedded on a Puppetfactory tab, this has the tendency to wrap and make the graph disappear when the screen is too small. This prevents the bounding box from shrinking that far. Scroll bars are preferable to invisible elements.
COURSES-2188 #resolved #time 30m
> Prevent view from wrapping on smaller screens

- public/css/style.css
- views/index.erb
Moved the admin login link out of the JqueryUI tabs.  It was
causing an infinite reload loop because of how it interacts with
the Sinatra redirect and the JqueryUI remote loading.
> (MAINT) Fix Admin Login Redirect Error

- lib/puppetfactory/plugins/docker.rb
This adds some additional mounts within the containers to provide more
yum repo caching. If the directory doesn't exist on the master, docker
will just create it, so this should be backwards compatible
> Map directories for yum cache

- puppetfactory.gemspec
Sinatra 2.0+ requires ruby 2.2+ this pins to the last version before 2.0
> Pin to older sinatra

- public/css/style.css
Because amber is impossible to see on a white background
> Change Link Colors to Blue

- lib/puppetfactory.rb
TRAINTECH-1302 #resolved #time 5d
Since both Puppetfactory and Abalone are Sinatra apps, whenever
the shell page was refreshed, their sessions conflicted.  This
specifies the session.key to prevent collision.
> (TRAINTECH-1302) Resolve Session Refresh Bug

- lib/puppetfactory.rb
Because IE over caches content, it would never reload the user page when you selected a user. This fixes that.
TRAINTECH-1219 #resolved #time 2h
> Disable caching

- bin/puppetfactory
With this commit, the default configuration doesn't provide a way for
users to log in. We never noticed, because we never run in the default
configuration.
> (maint) This enables a login action by default

- bin/puppetfactory
The Thin middleware server was timing out (30s by default) when the
classroom got loaded down. This caused the user creation to sometimes be
incomplete, and would lead to a poor user experience when they got raw
HTML squished into a popup dialog box!
The better solution is a progress bar, but that's out of scope for the
current sprint.
TRAINTECH-1392 #resolved #time 6h
> Increase Thin timeout

- lib/puppetfactory/plugins/gitea.rb
This way the `pfsh` shell still works for non-root users :)
TRAINTECH-1395 #resolved #time 20m
> Only write the lockfile when actually creating users

- public/js/scripts.js
jQuery doesn't reload a page when you switch to it unless needed. If
you're already on the desired page, it doesn't do anything.
TRAINTECH-1390 #resolved #time 15m
> Reload the page on user creation

- views/newuser.erb
- views/userlogin.erb
usermanagement.js was loaded in three times, causing it to attach
events to elements three times.
> (MAINT) Don't Load JS File Three Times

- lib/puppetfactory.rb
- public/js/usermanagement.js
TRAINTECH-1413 #resolved #time 8h
Resolves an issue where JS event listeners were not attached properly
and server side redirects were dropping port numbers. By using
JQuery event delegation, listeners are now attached to elements
that always exist, so lazy-loading does not cause any issues.
Removed the server side redirects since they were dropping port
numbers.
Added a little message in case user selection failed.
> (TRAINTECH-1413) Fix User Select and Logout Bug

- lib/puppetfactory/plugins/gitea.rb
If the admin's `~/.ssh` directory doesn't exist, then the `gitea` process will stack trace the first time you try to create a new user.
> (maint) Ensure that the admin's .ssh directory exists

- lib/puppetfactory/plugins/dashboard.rb
- lib/puppetfactory/plugins/gitea.rb
Code that should only be run during the server startup is now better
gated. This will prevent the permission error during user logins.
TRAINTECH-1420 #resolved #time 30m
> This prevents initialization from running as users

- bin/puppetfactory
The timeout option is only available when running with thin.
> (maint) only set timeout if server supports it

- views/logs.erb
The logs should scroll to the bottom and maintain that position. When the UI revamp occurred, this behavior was broken.
> (maint) restore broken scrolling behavior

- views/index.erb
TRAINTECH-1524 #resolved #time 2h
Fixes an issue where plugin tabs, including gitviz, were not
visible unless logged in as admin.
> (TRAINTECH-1524) Fix Plugin Tabs Issue

- lib/puppetfactory/plugins/gitea.rb
If `:gitea_upstream` is set in the config file, this will now respect
the setting.
TRAINTECH-1376 #resolved #time 30m
> Allow upstream repo to be configured

- public/css/style.css
This isn't truly a full solution because items that fall off if the
window is too narrow just disappear. A longer term solution would be to
be more responsive. But this is a good step to prevent the ugly
wrapping.
TRAINTECH-1463 #resolved #time 20m
> Prevent header wrapping

- lib/puppetfactory/plugins/gitea.rb
- templates/pre-receive.erb
This prevents users from committing to branches that are not their own.
This WILL prevent users from creating feature branches unless they're
named precisely following the format of "${username}-${branchname}"
> (maint) prevent cross branch commits

- lib/puppetfactory/plugins/gitea.rb
This allows the user to reclassify and configure a different control repository. Prior to this commit, it would never clone the second repository.
> (maint) check repository path, not just the cache dir
